apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: submission-portal
  namespace: argocd
spec:
  project: default
  revisionHistoryLimit: 1
  
  source:
    repoURL: https://github.com/2024h1120192p/project-submission-portal.git
    targetRevision: main
    path: k8s
    directory:
      recurse: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: paper-submission-portal
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
